### ISSUE TITLE
Issues with Synchrophasor example after S3DK installation in LabVIEW 2017

### ISSUE THREAD

**Issue by prottay** [ALSETLab/S3DK#2]
# Description
After S3DK installation using the latest executable, following libraries get broken. (To be more specific some files get over-written in the following paths.)

Program Files (x86)/National Instruments/LABVIEW 2017/vi.lib/addons/Electrical Power/PMU/
Program Files (x86)/National Instruments/LABVIEW 2017/vi.lib/addons/Electrical Power/Example Support/ 

In general they create no problem in running LabVIEW. But, when I tried running the Synchrophasor example (after installing S3DK) with NI cRIO-9082, the  NI_EP_PMU and NI_EP_PMU_FPGA libraries in the first path also got corrupted. 

# Fix-
The known fix (which I used) is to use the older versions of the two folders. After installing latest S3DK, I just replaced the two folders by copying them from another PC.

**Comment by MaximeBaudette** [comment]
Hi @prottay 

I checked my installation, and for both path you mention I didn't see any change.
Also the installation files of S3DK should not be making any use or install anything at that path.

Are you sure it is related to the installation of S3DK?
Could you reproduce it on another computer ?

**Comment by prottay** [comment]
Hi,

I managed to recreate the issue 2 times, on the same computer.

I will try in a different computer with a more updated version of LabVIEW
2017 and let you know

Prottay

Prottay M. Adhikari
(Senior Graduate Student,
Department of Electrical Engineering, IIT Bombay)

**Comment by prottay** [comment]
Hi,

I did the following steps on a fresh installation of LabVIEW. It is the
latest version now.

1. Install LabVIEW and all drivers.
2. Install S3Dk.
3. Implement PMU.

It worked fine on the latest version of LabVIEW.  I did not have the
problem I described earlier.

I am suspecting it was not an S3Dk issue but a LabVIEW issue (for older
versions of 2017), which got fixed after their patch releases of 2017 May
and 2017 December.

Prottay

**Comment by MaximeBaudette** [comment]
Great, 
Happy to hear that! Then I'm gonna c;lose this issue.

**Comment by prottay** [comment]
Hi,
I think the issue can be closed now as there seems to be no direct
compatibility issue.

However, just to be doubly sure, I will run a new set of experiment with
the following flow and check if the issue comes up

1. Install LabVIEW and all drivers.
2. Implement PMU.  [Before installing S3Dk]
3. Install S3Dk.

I will update you once, I have the results.
Prottay
