### ISSUE TITLE
64-Bit Compatibility Work-Around

### ISSUE THREAD

**Issue by lvanfretti** [ALSETLab/S3DK#4]
When running on 64-bit Windows 10 LabVIEW will give errors when trying to use any of the pallete's blocks of the S3DK.

The current release does not include the 64-bit build of the "StrongridDLL.dll", but a 32-bit build. So, this needs to be replaced with a 64-bit build.

The proposed work-around is: 
  1 - Go to the folder
`C:\Program Files\National Instruments\LabVIEW 2017\vi.lib\S3DK\data`
  2 - Delete the file `StrongridDLL.dll`
  3 - Download the 64-bit versioin of the  StrongridDLL.dll from: [https://github.com/ALSETLab/S3DK-STRONGgrid/releases/tag/V0.1-alpha](https://github.com/ALSETLab/S3DK-STRONGgrid/releases/tag/V0.1-alpha)
  4 - Take the `StrongridDLL.dll` file you downloaded in step 3 above and copy/paste to the folder`C:\Program Files\National Instruments\LabVIEW 2017\vi.lib\S3DK\data`

I have tested this under LabVIEW 2017 64-bit  under Windows 10.

The next release will only support LabVIEW 2017 under 64-bit.
![screenshot 2018-06-13 17 17 22](https://user-images.githubusercontent.com/7248948/41378659-bb1e7d22-6f2d-11e8-9d88-a31dbe503a0a.png)

**Comment by MaximeBaudette** [comment]
I have now implemented the workaround in one package called s3dk_x64
Essentially I have both versions of the DLL in the project, and in the specific package I added a command to move StrongridDLLx64 and rename it to StrongridDLL, overwriting the other DLL. 

Please test as I don't have the setup to test myself

**Comment by MaximeBaudette** [comment]
https://github.com/ALSETLab/S3DK/releases/tag/v1.3.0

**Comment by lvanfretti** [comment]
@Grey-J please test

**Comment by Grey-J** [comment]
Yeah the work around seems to work  well.

**Comment by lvanfretti** [comment]
@Grey-J Did you test the new realease that Maxime did or the workaround?
Please test the new release:
https://github.com/ALSETLab/S3DK/releases/tag/v1.3.0

**Comment by Grey-J** [comment]
Yes I meant the new release that Maxime uploaded not the work around., it works just the same as the work around from what I tested.

**Comment by MaximeBaudette** [comment]
That's great to hear! I'm guess I'm gonna close the issue for now then

**Comment by lvanfretti** [comment]
@Grey-J thanks!
