### ISSUE TITLE
S3DK.lvlib

### ISSUE THREAD

**Issue by samil07** [ALSETLab/S3DK#6]
Hi there, 
I am having some difficulties with S3DK. I could build the package and install it with VIPM. However, i cannot see the neccessary VIs on function palette, not all of them indeed. The ones that appear in function palette have question mark icon.  I guess the reason is that S3DK.lvlib cannot be installed since when i open the S3DK Compiler project, it can't find the S3DK.lvlib. I try to find it in vi.lib folder but it does not reside there. Could you please help me figure out the problem?

**Comment by lvanfretti** [comment]
@samil07 sorry I didn't see this until now, please see my quickstart guide:
https://www.notion.so/alsetlab/Quick-Start-Guide-Installing-the-S3DK-and-Testing-your-Installation-f791d8c2e9d7402ab6a820e065dd93e2
